version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    container_name: php-app

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: gestionboutique
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    container_name: mysql-db

networks:
  app-network:

volumes:
  mysql-data:
