services:
  App\Database\PDOConnection:
    class: PDO
    arguments:
      - 'mysql:host=localhost;dbname=gestionboutique'
      - 'testuser'
      - 'Csmuzumaki123!!'

  App\Database\MysqlDatabase:
    class: App\Database\MysqlDatabase
    arguments:
      - '@App\Database\PDOConnection'

  App\Security\SecurityDatabase:
    class: App\Security\SecurityDatabase
    arguments:
      - '@App\Database\MysqlDatabase'
      - '@App\Authorize\Authorize'
      - '@App\Files\FileHandler'
      - '@App\Session\Session'



  App\Database\Database:
    factory: '@App\Database\MysqlDatabase'  # Utiliser MysqlDatabase comme service 'database'

  App\Authorize\Authorize:
    class: App\Authorize\Authorize
    arguments: []

  App\Files\FileHandler:
    class: App\Files\FileHandler
    arguments: []

  App\Model\ClientModel:
    class: App\Model\ClientModel
    arguments:
      - '@App\Database\MysqlDatabase'

  App\Model\UtilisateurModel:
    class: App\Model\UtilisateurModel
    arguments:
      - '@App\Database\MysqlDatabase'

  App\Model\DebtModel:
    class: App\Model\DebtModel
    arguments:
      - '@App\Database\MysqlDatabase'

  App\Model\ProduitsModel:
    class: App\Model\ProduitsModel
    arguments:
      - '@App\Database\MysqlDatabase'

  App\Model\PaiementModel:
    class: App\Model\PaiementModel
    arguments:
      - '@App\Database\MysqlDatabase'    

  App\Routes\WebRoutes:
    class: App\Routes\WebRoutes  # Définition des routes web

  App\Routes\ApiRoutes:
    class: App\Routes\ApiRoutes  # Définition des routes API

  App\Session\Session:
    class: App\Session\Session
    arguments: []

  App\Controller\Controller:
    class: App\Controller\Controller
    arguments:
      - '@App\Authorize\Authorize'
      - '@App\Files\FileHandler'
      - '@App\Session\Session'
      - false

  App\Controller\ClientController:
    class: App\Controller\ClientController
    arguments:
      - '@App\Authorize\Authorize'
      - '@App\Files\FileHandler'
      - '@App\Model\ClientModel'
      - '@App\Model\UtilisateurModel'
      - '@App\Model\DebtModel'
      - '@App\Session\Session'

  App\Controller\DebtController:
    class: App\Controller\DebtController
    arguments:
      - '@App\Authorize\Authorize'
      - '@App\Files\FileHandler'
      - '@App\Model\DebtModel'  # Assurez-vous que c'est bien DebtModel ici
      - '@App\Session\Session'
      - '@App\Model\ClientModel'
      - '@App\Model\ProduitsModel'
      - '@App\Model\UtilisateurModel'
      - '@App\Model\PaiementModel'

  App\Controller\LoginController:
    class: App\Controller\LoginController
    arguments:
    - '@App\Security\SecurityDatabase'

  router:
    class: App\Core\Router
    arguments:
      - '@App\Routes\WebRoutes'
      - '@App\Routes\ApiRoutes'
      - '@App\Authorize\Authorize'
      - '@App\Files\FileHandler'
      - '@service_container'  # Assurez-vous que ce service est chargé correctement